name: Run main.py and commit results

# 触发条件：在推送（push）到默认分支时运行
on:
  push:
    branches:
      - master # 默认分支名
  schedule:
    - cron: "*/5 * * * *" # 每5分钟执行一次（TUC时间）
    # - cron: "*/10 * * * *" # 每10分钟执行一次（TUC时间）

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Python版本
          cache: "pip" # 使用缓存

      - name: Install dependencies
        run: pip install -r requirements.txt # 依赖文件

      - name: Run main.py
        run: python main.py # 要运行的Python脚本

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S %Z"
          BEIJING_TIME=$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S %Z")
          git add .
          git commit -m "$BEIJING_TIME"
          git pull
          git push -u origin master
